---

- name: Ensure GitOps Namespace
  community.okd.k8s:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      name: "{{ gitops.namespace }}"
      metadata:
        name: "{{ gitops.namespace }}"

- name: Ensure ARGOCD Subscription
  community.okd.k8s:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    state: "{{ state }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ gitops.namespace }}"
        namespace: "{{ operators.gitops.namespace }}"
      spec:
        config:
          env:
          - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
            value: "{{ gitops.namespace }}"
        channel: "{{ operators.gitops.channel }}"
        installPlanApproval: Automatic
        name: "openshift-gitops-operator"
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Ensure Creator RBAC
  community.okd.k8s:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    state: "{{ state }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{ gitops.namespace }}-cluster-admin-binding"
      subjects:
        - kind: ServiceAccount
          name: "{{ gitops.namespace }}-argocd-application-controller"
          namespace: "{{ gitops.namespace }}"
      roleRef:
        kind: ClusterRole
        name: cluster-admin
        apiGroup: rbac.authorization.k8s.io

- name: OpenShift GitOps - Wait for CRD Exists
  community.kubernetes.k8s_info:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "argocds.argoproj.io"
  register: argocd_crd
  until: argocd_crd.resources | length > 0
  retries: 10
  delay: 10

- name: Patch ArgoCD Custom Resource to Enable Helm
  community.okd.k8s:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    state: "{{ state }}"
    definition:
      apiVersion: argoproj.io/v1beta1
      kind: ArgoCD
      metadata:
        name: "{{ gitops.namespace }}"
        namespace: "{{ gitops.namespace }}"
      spec:
        server:
          route:
            enabled: true
        kustomizeBuildOptions: '--enable-helm'
