---

## Install Keycloak for TSSC
- name: Keycloak - Install Keycloak
  community.okd.k8s:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    state: "{{ state }}"
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "keycloak-plugin"
        namespace: "{{ openshift.services.gitops.namespace }}"
      spec:
        destination:
          namespace: "keycloak"
          server: 'https://kubernetes.default.svc'
        source:
          chart: keycloak
          repoURL: "https://poc-examples.github.io/charts"
          version: v3
          targetRevision: "{{ openshift.services.keycloak.chartVersion }}"
          helm:
            valuesObject:
              domain: "{{ openshift.domain }}"
        project: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          managedNamespaceMetadata:
            labels:
              argocd.argoproj.io/managed-by: "{{ openshift.services.gitops.namespace }}"
          syncOptions:
            - CreateNamespace=true
            - Validate=false
            - SkipDryRunOnMissingResource=true
