---

## Install External Secrets From Helm Charts 
## AS ARGOCD APPLICATION
- name: GitLab - Install Application
  community.okd.k8s:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    state: "{{ state }}"
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "gitlab-plugin"
        namespace: "{{ gitops.namespace }}"
      spec:
        destination:
          namespace: "{{ openshift.services.gitlab.helmValues.namespace }}"
          server: 'https://kubernetes.default.svc'
        source:
          repoURL: "https://github.com/poc-examples/charts"
          path: "gitlab"
          version: v3
          targetRevision: HEAD
          helm:
            valuesObject:  "{{ openshift.services.gitlab.helmValues }}"
        project: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          managedNamespaceMetadata:
            labels:
              argocd.argoproj.io/managed-by: "{{ gitops.namespace }}"
          syncOptions:
            - CreateNamespace=true
            - Validate=false
            - SkipDryRunOnMissingResource=true

## VERIFY EXTERNAL SECRETS IS RUNNING BEFORE CONTINUING
- name: GitLab - Wait Webserver Exists
  community.kubernetes.k8s_info:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    kind: Deployment
    name: "gitlab-webservice-default"  # Replace with your actual deployment name
    namespace: "gitlab-system"  # Replace with the actual namespace
  register: gitlab_webserver_status
  until:
    - gitlab_webserver_status.resources | length > 0
    - gitlab_webserver_status.resources[0].status.readyReplicas | default(0) == gitlab_webserver_status.resources[0].status.replicas
  retries: 40
  delay: 15
