---

- name: Install Required Packages
  apt:
    name:
      - "bind9"
      - "apt-transport-https"
    state: present

- name: Configure named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9 service

- name: Configure arpa zone
  ansible.builtin.template:
    src: in-addr.arpa.zone.j2
    dest: /etc/bind/{{ arpa_zone }}.in-addr.arpa.zone
  notify: Restart bind9 service

# - name: Configure application internal.zone
#   ansible.builtin.template:
#     src: in-addr.arpa.zone.j2
#     dest: /etc/bind/in-addr.arpa.zone

# - name: Configure cluster internal.zone
#   ansible.builtin.template:
#     src: cluster.internal.zone.j2
#     dest: /etc/bind/cluster.internal.zone

- name: Set ownership and permissions for /etc/bind/
  ansible.builtin.file:
    path: /etc/bind/
    owner: bind
    group: bind
    mode: '0755'
    recurse: yes
  notify: Restart bind9 service

- name: Flush Handlers to Restart BIND Service Now
  meta: flush_handlers

- name: Add nameserver to /etc/resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    insertbefore: BOF
    line: "nameserver {{ dns_ip }}"