---

## Install External Secrets From Helm Charts 
## AS ARGOCD APPLICATION
- name: External Secrets - Install Application
  community.okd.k8s:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    state: "{{ state }}"
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "external-secrets-plugin"
        namespace: "{{ openshift.services.gitops.namespace }}"
      spec:
        destination:
          namespace: "{{ openshift.services.external_secrets.namespace }}"
          server: 'https://kubernetes.default.svc'
        source:
          chart: external_secrets
          repoURL: "https://poc-examples.github.io/charts"
          version: v3
          targetRevision: 0.1.7
          helm:
            valuesObject:  "{{ openshift.services.external_secrets.helmValues }}"
        project: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          managedNamespaceMetadata:
            labels:
              argocd.argoproj.io/managed-by: "{{ openshift.services.gitops.namespace }}"
          syncOptions:
            - CreateNamespace=true
            - Validate=false
            - SkipDryRunOnMissingResource=true

## VERIFY EXTERNAL SECRETS IS RUNNING BEFORE CONTINUING
- name: External Secrets - Wait Webhook is Running
  community.kubernetes.k8s_info:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    kind: Deployment
    name: "{{ openshift.services.external_secrets.namespace }}-webhook"
    namespace: "{{ openshift.services.external_secrets.namespace }}"
  register: operator_status
  until:
    - operator_status.resources | length > 0
    - operator_status.resources[0].status.readyReplicas | default(0) > 0
  retries: 20
  delay: 25
