apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    name: root-app-of-apps
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/poc-examples/app-of-apps'
    path: '.'
    version: v3
    targetRevision: HEAD
  project: default
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: false
