---

## Install External Secrets From Helm Charts 
## AS ARGOCD APPLICATION
- name: DevHub - Install Application
  community.okd.k8s:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    state: "{{ state }}"
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "devhub-plugin"
        namespace: "{{ gitops.namespace }}"
      spec:
        destination:
          namespace: "backstage"
          server: 'https://kubernetes.default.svc'
        source:
          repoURL: "https://github.com/poc-examples/charts"
          path: "developer_hub"
          version: v3
          targetRevision: HEAD
          helm:
            valuesObject:
              host: "{{ openshift.domain }}"
        project: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          managedNamespaceMetadata:
            labels:
              argocd.argoproj.io/managed-by: "{{ gitops.namespace }}"
          syncOptions:
            - CreateNamespace=true
            - Validate=false
            - SkipDryRunOnMissingResource=true

## VERIFY EXTERNAL SECRETS IS RUNNING BEFORE CONTINUING
- name: DevHub - Wait Webserver Exists
  community.kubernetes.k8s_info:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    kind: Deployment
    name: "backstage-developer-hub"  # Replace with your actual deployment name
    namespace: "backstage"  # Replace with the actual namespace
  register: devhub_webserver_status
  until:
    - devhub_webserver_status.resources | length > 0
    - devhub_webserver_status.resources[0].status.readyReplicas | default(0) == devhub_webserver_status.resources[0].status.replicas
  retries: 40
  delay: 15
