---

## Install SonarQube
- name: SonarQube - Install SonarQube
  community.okd.k8s:
    host: "{{ openshift.api_url }}"
    api_key: "{{ openshift.token }}"
    validate_certs: "{{ openshift.validate_certs }}"
    state: "{{ state }}"
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "sonarqube-plugin"
        namespace: "{{ openshift.services.gitops.namespace }}"
      spec:
        destination:
          namespace: "sonarqube"
          server: 'https://kubernetes.default.svc'
        source:
          chart: sonarqube
          repoURL: "https://SonarSource.github.io/helm-chart-sonarqube"
          version: v3
          targetRevision: "{{ openshift.services.sonarqube.chartVersion }}"
          helm:
            parameters:
              - name: OpenShift.enabled
                value: "true"
              - name: serviceAccount.create
                value: "true"
              - name: postgresql.serviceAccount.enabled
                value: "true"
              - name: route.enabled
                value: "true"
        project: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          managedNamespaceMetadata:
            labels:
              argocd.argoproj.io/managed-by: "{{ openshift.services.gitops.namespace }}"
          syncOptions:
            - CreateNamespace=true
            - Validate=false
            - SkipDryRunOnMissingResource=true
